local properties = {
	ScreenGui = {
		--data
		'DisplayOrder',
		'Enabled',
		'IgnoreGuiInset',
		'Name',
		'Parent',
		'ResetOnSpawn',
		'ZIndexBehavior',
		--behavior
		'Archivable',
		--Localiztation
		'AutoLocalize',
		'RootLocalizationTable'
	},
	TextButton = {
		--data
		'Active',
		'AnchorPoint',
		'AutoButtonColor',
		'AutomaticSize',
		'BackgroundColor3',
		'BackgroundTransparency',
		'BorderColor3',
		'BorderMode',
		'BorderSizePixel',
		'LayoutOrder',
		'Modal',
		'Name',
		'Parent',
		'Position',
		'Rotation',
		'Selectable',
		'Selected',
		'Size',
		'SizeConstraint',
		'Style',
		'Visible',
		'ZIndex',
		--behavior
		'Archivable',
		'ClipsDescendants',
		'NextSelectionDown',
		'NextSelectionLeft',
		'NextSelectionRight',
		'NextSelectionUp',
		--text
		'Font',
		'LineHeight',
		'MaxVisibleGraphemes',
		'RichText',
		'Text',
		'TextColor3',
		'TextScaled',
		'TextSize',
		'TextStrokeColor3',
		'TextStrokeTransparency',
		'TextTransparency',
		'TextTruncate',
		'TextWrapped',
		'TextXAlignment',
		'TextYAlignment',
		--localization
		'AutoLocalize',
		'RootLocalizationTable'
	},
	TextLabel = {
		--data
		'Active',
		'AnchorPoint',
		'AutomaticSize',
		'BackgroundColor3',
		'BackgroundTransparency',
		'BorderColor3',
		'BorderMode',
		'BorderSizePixel',
		'LayoutOrder',
		'Name',
		'Parent',
		'Position',
		'Rotation',
		'Selectable',
		'Size',
		'SizeConstraint',
		'Visible',
		'ZIndex',
		--behavior
		'Archivable',
		'ClipsDescendants',
		'NextSelectionDown',
		'NextSelectionLeft',
		'NextSelectionRight',
		'NextSelectionUp',
		--text
		'Font',
		'LineHeight',
		'MaxVisibleGraphemes',
		'RichText',
		'Text',
		'TextColor3',
		'TextScaled',
		'TextSize',
		'TextStrokeColor3',
		'TextStrokeTransparency',
		'TextTransparency',
		'TextTruncate',
		'TextWrapped',
		'TextXAlignment',
		'TextYAlignment',
		--localization
		'AutoLocalize',
		'RootLocalizationTable'
	},
	TextBox = {
		--data
		'Active',
		'AnchorPoint',
		'AutomaticSize',
		'BackgroundColor3',
		'BackgroundTransparency',
		'BorderColor3',
		'BorderMode',
		'BorderSizePixel',
		'ClearTextOnFocus',
		'LayoutOrder',
		'MultiLine',
		'Name',
		'Parent',
		'Position',
		'Rotation',
		'Selectable',
		'SelectionStart',
		'ShowNativeInput',
		'Size',
		'SizeConstraint',
		'Visible',
		'ZIndex',
		--behavior
		'Archivable',
		'ClipsDescendants',
		'NextSelectionDown',
		'NextSelectionLeft',
		'NextSelectionRight',
		'NextSelectionUp',
		--text
		'Font',
		'LineHeight',
		'MaxVisibleGraphemes',
		'PlaceholderColor3',
		'PlaceholderText',
		'RichText',
		'Text',
		'TextColor3',
		'TextScaled',
		'TextSize',
		'TextStrokeColor3',
		'TextStrokeTransparency',
		'TextTransparency',
		'TextTruncate',
		'TextWrapped',
		'TextXAlignment',
		'TextYAlignment',
		--localization
		'AutoLocalize',
		'RootLocalizationTable'
	},
	ImageLabel = {
		--data
		'Active',
		'AnchorPoint',
		'AutomaticSize',
		'BackgroundColor3',
		'BackgroundTransparency',
		'BorderColor3',
		'BorderMode',
		'BorderSizePixel',
		'LayoutOrder',
		'Name',
		'Parent',
		'Position',
		'Rotation',
		'Selectable',
		'Size',
		'SizeConstraint',
		'Visible',
		'ZIndex',
		--behavior
		'Archivable',
		'ClipsDescendants',
		'NextSelectionDown',
		'NextSelectionLeft',
		'NextSelectionRight',
		'NextSelectionUp',
		--Image
		'Image',
		'ImageColor3',
		'ImageRectOffset',
		'ImageRectSize',
		'ImageTransparency',
		'ScaleType',
		'SliceScale',
		--localization
		'AutoLocalize',
		'RootLocalizationTable'
	},
	ImageButton = {
		--data
		'Active',
		'AnchorPoint',
		'AutoButtonColor',
		'AutomaticSize',
		'BackgroundColor3',
		'BackgroundTransparency',
		'BorderColor3',
		'BorderMode',
		'BorderSizePixel',
		'LayoutOrder',
		'Modal',
		'Name',
		'Parent',
		'Position',
		'Rotation',
		'Selectable',
		'Selected',
		'Size',
		'SizeConstraint',
		'Style',
		'Visible',
		'ZIndex',
		--behavior
		'Archivable',
		'ClipsDescendants',
		'NextSelectionDown',
		'NextSelectionLeft',
		'NextSelectionRight',
		'NextSelectionUp',
		--Image
		'HoverImage',
		'Image',
		'ImageColor3',
		'ImageRectOffset',
		'ImageRectSize',
		'ImageTransparency',
		'ScaleType',
		'SliceScale',
		--localization
		'AutoLocalize',
		'RootLocalizationTable'
	},
	Frame = {
		--data
		'Active',
		'AnchorPoint',
		'AutomaticSize',
		'BackgroundColor3',
		'BackgroundTransparency',
		'BorderColor3',
		'BorderMode',
		'BorderSizePixel',
		'LayoutOrder',
		'Name',
		'Parent',
		'Position',
		'Rotation',
		'Selectable',
		'Size',
		'SizeConstraint',
		'Style',
		'Visible',
		'ZIndex',
		--behavior
		'Archivable',
		'ClipsDescendants',
		'NextSelectionDown',
		'NextSelectionLeft',
		'NextSelectionRight',
		'NextSelectionUp',
		--localization
		'AutoLocalize',
		'RootLocalizationTable'
	},
	ScrollingFrame = {
		--data
		'Active',
		'AnchorPoint',
		'AutomaticSize',
		'BackgroundColor3',
		'BackgroundTransparency',
		'BorderColor3',
		'BorderMode',
		'BorderSizePixel',
		'LayoutOrder',
		'Name',
		'Parent',
		'Position',
		'Rotation',
		'Selectable',
		'Size',
		'SizeConstraint',
		'Visible',
		'ZIndex',
		--behavior
		'Archivable',
		'ClipsDescendants',
		'NextSelectionDown',
		'NextSelectionLeft',
		'NextSelectionRight',
		'NextSelectionUp',
		--scrolling
		'AutomaticCanvasSize',
		'BottomImage',
		'CanvasPosition',
		'CanvasSize',
		'ElasticBehavior',
		'HorizontalScrollBarInset',
		'MidImage',
		'ScrollBarImageColor3',
		'ScrollBarImageTransparency',
		'ScrollBarThickness',
		'ScrollingDirection',
		'ScrollingEnabled',
		'TopImage',
		'VerticalScrollBarInset',
		'VerticalScrollBarPosition',
		--localization
		'AutoLocalize',
		'RootLocalizationTable'
	},
	LocalScript = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
		'Disabled'
	},
	ModuleScript = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
	},
	UIGradient = {
		--appearance
		'Color',
		'Enabled',
		'Offset',
		'Rotation',
		'Transparency',
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable'
	},
	UICorner = {
		--appearance
		'CornerRadius',
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
	},
	UIAspectRatioConstraint = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
		'AspectRatio',
		'AspectType',
		'DominantAxis'
	},
	UIGridLayout = {
		--appearance
		'CellPadding',
		'CellSize',
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
		'FillDirection',
		'FillDirectionMaxCells',
		'HorizontalAlignment',
		'SortOrder',
		'StartCorner',
		'VerticalAlignment'
	},
	UIListLayout = {
		--appearance
		'Padding',
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
		'FillDirection',
		'HorizontalAlignment',
		'SortOrder',
		'VerticalAlignment'
	},
	UIPadding = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
		'PaddingBottom',
		'PaddingLeft',
		'PaddingRight',
		'PaddingTop'
	},
	UIPageLayout = {
		--appearance
		'Animated',
		'Circular',
		'EasingDirection',
		'EasingStyle',
		'Padding',
		'TweenTime',
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
		'FillDirection',
		'HorizontalAlignment',
		'SortOrder',
		'VerticalAlignment',
		--input
		'GamepadInputEnabled',
		'ScrollWheelInputEnabled',
		'TouchInputEnabled'
	},
	UIScale = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
		'Scale'
	},
	UIStroke = {
		--appearence
		'ApplyStrokeMode',
		'Color',
		'LineJoinMode',
		'Thickness',
		'Transparency',
		--data
		'Enabled',
		'Name',
		'Parent',
		--behavior
		'Archivable',
	},
	UISizeConstraint = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
		'MaxSize',
		'MinSize'
	},
	UITableLayout = {
		--appearance
		'FillEmptySpaceColumns',
		'FillEmptySpaceRows',
		'Padding',
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
		'FillDirection',
		'HorizontalAlignment',
		'MajorAxis',
		'SortOrder',
		'VerticalAlignment'
	},
	UITextSizeConstraint = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
		'MaxTextSize',
		'MinTextSize'
	},
	VideoFrame = {
		--appearance
		'SelectionImageObject',
		--data
		'Active',
		'AnchorPoint',
		'AutomaticSize',
		'BackgroundColor3',
		'BackgroundTransparency',
		'BorderColor3',
		'BorderMode',
		'BorderSizePixel',
		'LayoutOrder',
		'Name',
		'Parent',
		'Position',
		'Rotation',
		'Selectable',
		'Size',
		'SizeConstraint',
		'Visible',
		'ZIndex',
		--behavior
		'Archivable',
		'ClipsDescendants',
		'NextSelectionDown',
		'NextSelectionLeft',
		'NextSelectionRight',
		'NextSelectionUp',
		--video
		'Looped',
		'Playing',
		'Resolution',
		'TimeLength',
		'TimePosition',
		'Video',
		'Volume',
		--localization
		'AutoLocalize',
		'RootLocalizationTable'
	},
	ViewportFrame = {
		--appearance
		'Ambient',
		'LightColor',
		'LightDirection',
		'SelectionImageObject',
		--data
		'Active',
		'AnchorPoint',
		'AutomaticSize',
		'BackgroundColor3',
		'BackgroundTransparency',
		'BorderColor3',
		'BorderMode',
		'BorderSizePixel',
		'CurrentCamera',
		'LayoutOrder',
		'Name',
		'Parent',
		'Position',
		'Rotation',
		'Selectable',
		'Size',
		'SizeConstraint',
		'Visible',
		'ZIndex',
		--behavior
		'Archivable',
		'ClipsDescendants',
		'NextSelectionDown',
		'NextSelectionLeft',
		'NextSelectionRight',
		'NextSelectionUp',
		--image
		'ImageColor3',
		'ImageTransparency',
		--localization
		'AutoLocalize',
		'RootLocalizationTable'
	},
	BillboardGui = {
		--data
		'Active',
		'Adornee',
		'AlwaysOnTop',
		'Enabled',
		'ExtentsOffset',
		'ExtentsOffsetWorldSpace',
		'LightInfluence',
		'MaxDistance',
		'Name',
		'Parent',
		'PlayerToHideFrom',
		'ResetOnSpawn',
		'Size',
		'SizeOffset',
		'StudsOffset',
		'StudsOffsetWorldSpace',
		'ZIndexBehavior',
		--behavior
		'Archivable',
		'ClipsDescendants',
		--localization
		'AutoLocalize',
		'RootLocalizationTable'
	},
	Hint = {
		--appearance
		'Text',
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable'
	},
	Message = {
		--appearance
		'Text',
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable'
	},
	BoolValue = {
		--data
		'Name',
		'Parent',
		'Value',
		--behavior
		'Archivable'
	},
	BrickColorValue = {
		--data
		'Name',
		'Parent',
		'Value',
		--behavior
		'Archivable'
	},
	CFrameValue = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable'
	},
	Color3Value = {
		--data
		'Name',
		'Parent',
		'Value',
		--behavior
		'Archivable'
	},
	IntValue = {
		--data
		'Name',
		'Parent',
		'Value',
		--behavior
		'Archivable'
	},
	NumberValue = {
		--data
		'Name',
		'Parent',
		'Value',
		--behavior
		'Archivable'
	},
	ObjectValue = {
		--data
		'Name',
		'Parent',
		'Value',
		--behavior
		'Archivable'
	},
	RayValue = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable'
	},
	StringValue = {
		--data
		'Name',
		'Parent',
		'Value',
		--behavior
		'Archivable'
	},
	Vector3Value = {
		--data
		'Name',
		'Parent',
		'Value',
		--behavior
		'Archivable'
	},
	Part = {
		--appearance
		'BrickColor',
		'CastShadow',
		'Color',
		'Material',
		'Reflectance',
		'Transparency',
		--data
		'Name',
		'Orientation',
		'Parent',
		'Position',
        --[[--transform
        'Origin Position',
        'Origin Orientation',
        --pivot
        'Pivot Offset Position',
        'Pivot Offset Orientation',]]
		--behavior
		'Anchored',
		'Archivable',
		'CanCollide',
		'CanTouch',
		'CollisionGroupId',
		'Locked',
		'Massless',
		--part
		'CustomPhysicalProperties',
		'RootPriority',
		'Shape',
		'Size',
		--assembly
		'AssemblyLinearVelocity',
		'AssemblyAngularVelocity'
	},
	MeshPart = {
		--appearance
		'BrickColor',
		'CastShadow',
		'Color',
		'DoubleSided',
		'Material',
		'MeshId',
		'Reflectance',
		'RenderFidelity',
		'TextureID',
		'Transparency',
		--data
		'Name',
		'Orientation',
		'Parent',
		'Position',
        --[[--transform
        'Origin Position',
        'Origin Orientation',
        --pivot
        'Pivot Offset Position',
        'Pivot Offset Orientation',]]
		--behavior
		'Anchored',
		'Archivable',
		'CanCollide',
		'CanTouch',
		'CollisionFidelity',
		'CollisionGroupId',
		'Locked',
		'Massless',
		--part
		'CustomPhysicalProperties',
		'RootPriority',
		'Size',
		--assembly
		'AssemblyLinearVelocity',
		'AssemblyAngularVelocity'
	},
	Humanoid = {
		--data
		'CameraOffset',
		'DisplayDistanceType',
		'DisplayName',
		'HealthDisplayDistance',
		'HealthDisplayType',
		'Name',
		'NameDisplayDistance',
		'NameOcclusion',
		'Parent',
		'RigType',
		--behavior
		'Archivable',
		'BreakJointsOnDeath',
		'RequiresNeck',
		--jump settings
		'AutoJumpEnabled',
		'JumpPower',
		'UseJumpPower',
		--control
		'AutoRotate',
		'Jump',
		'PlatformStand',
		'Sit',
		'TargetPoint',
		'WalkToPart',
		'WalkToPoint',
		--game
		'AutomaticScalingEnabled',
		'Health',
		'HipHeight',
		'MaxHealth',
		'MaxSlopeAngle',
		'WalkSpeed'
	},
	BoxHandleAdornment = {
		--appearance
		'Color3',
		'Transparency',
		--data
		'AdornCullingMode',
		'Adornee',
		'AlwaysOnTop',
		'Name',
		'Parent',
		'Size',
		'SizeRelativeOffset',
		'Visible',
		'ZIndex',
		--behavior
		'Archivable'
	},
	BindableEvent = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
	},
	BindableFunction = {
		--data
		'Name',
		'Parent',
		--behavior
		'Archivable',
	},
	Configuration = {
		--data
		'Archivable',
		'Name',
		'Parent',
	},
	Folder = {
		--data
		'Archivable',
		'Name',
		'Parent',
	},
}

return properties
